### PR TITLE
fix: Configuration object was being coppied when a new PageURLS objec…

### LINKED ISSUE #1701: PageUrl Configuration not being updated
Previously I could use getConfiguration().setDefaultBaseUrl(baseUrl); to set the base URL of the application programatically, then after that if i called a paramatised open on a page object with a named URL, the base URL would be appended so the overall url would be _baseURL + namedUrl_.

However, after updating to 2.0.49 it seems the configuration that is on the PageUrls object, does not match that returned by the ConfiguredEnvironment.getConfiguration() if the configuration has been updated.

Is this a intended design or are there any changes anyone is aware of that could have broke this?

Here is an example where the configuration returned by the ConfiguredEnvironment.getConfiguration() call is different to the one on the PageUrls object: 
image

### PR DESCRIPTION
**Pull request by Azer249**
Fixes #1701

#### Summary of this PR

Instead of creating a new instance of a Configuration so that the environment variables can be re-set, the environment variables have been changed to none final, and can be set using the withEnvironmentVariables method. 

#### Intended effect

When updating the environment variables, the current configuration object will be updated instead of creating an entirely new object just to update the environment variables. 

#### How should this be manually tested?

There is a sample project in issue #1701 that can be used to debug the configuration. 

After this change has been applied the configuration returned by ConfiguredEnvironment.getConfiguration() should be the same object as the Configuration stored on any PageUrls object, and any changes made to the configuration should be visible on the Configuration when accessed via either of these places. 

#### Relevant tickets

 issue #1701

#### Screenshots (if appropriate)

Before the pull request the object reference will be different when checking the configuration:
image

After the pull request the object reference will be the same:

image

### CODE REVIEW

File: serenity-core/src/main/java/net/thucydides/core/configuration/WebDriverConfiguration.java [hunk 1]
```diff
@@ -58,19 +58,4 @@ private void throwUnsupportedDriverExceptionFor(final String driverType) {
                 + " is not a supported browser. Supported driver values are: "
                 + SupportedWebDriver.listOfSupportedDrivers());
     }
-
-    @Override
-    public WebDriverConfiguration copy() {
```
Comment (Azer249) [inline serenity-core/src/main/java/net/thucydides/core/configuration/WebDriverConfiguration.java]: Removed the copy function - it was only used as a workaround to update the environment variables

File: serenity-core/src/test/java/net/thucydides/core/webdriver/WhenManagingGlobalConfiguration.java [hunk 2]
```diff
@@ -28,16 +28,6 @@ public void the_step_delay_value_can_be_defined_in_a_system_property() {
         assertThat(configuration.getStepDelay(), is(1000));
     }
 
-    @Test
-    public void a_configuration_can_be_safely_copied() {
```
Comment (Azer249) [inline serenity-core/src/test/java/net/thucydides/core/webdriver/WhenManagingGlobalConfiguration.java]: Since the copy function has been removed this test is no longer needed

File: serenity-model/src/main/java/net/thucydides/core/configuration/SystemPropertiesConfiguration.java [hunk 3]
```diff
@@ -61,7 +61,7 @@
 
     protected String defaultBaseUrl;
 
-    private final EnvironmentVariables environmentVariables;
+    protected EnvironmentVariables environmentVariables;
```
Comment (Azer249) [inline serenity-model/src/main/java/net/thucydides/core/configuration/SystemPropertiesConfiguration.java]: Changed this to none final so instead, the environment variables can be maintained on the same instance of the configuration

File: serenity-model/src/main/java/net/thucydides/core/configuration/SystemPropertiesConfiguration.java [hunk 4]
```diff
@@ -71,25 +71,17 @@ public SystemPropertiesConfiguration(EnvironmentVariables environmentVariables)
...
-
-
-    public Configuration withEnvironmentVariables(EnvironmentVariables environmentVariables) {
-        SystemPropertiesConfiguration copy = new SystemPropertiesConfiguration(environmentVariables.copy());
-        copy.outputDirectory = null; // Reset to be reloaded from the System properties
-        copy.defaultBaseUrl = defaultBaseUrl;
-        return copy;
+    @Override
+    public SystemPropertiesConfiguration withEnvironmentVariables(final EnvironmentVariables environmentVariables) {
+        this.environmentVariables = environmentVariables;
```
Comment (Azer249) [inline serenity-model/src/main/java/net/thucydides/core/configuration/SystemPropertiesConfiguration.java]: Update the environment variables on the current instance of the object then return a reference to itself.
